# Generated by Django 5.2.3 on 2025-06-29 04:23

import theater.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theater", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="avatar",
            field=models.ImageField(
                default="actors/default.jpg",
                upload_to=theater.models.actor_directory_path,
            ),
        ),
    ]
