# Generated by Django 5.2.3 on 2025-07-06 02:14

import theater.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theater", "0003_actor_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="play",
            name="image",
            field=models.ImageField(
                default="img/plays/default.jpg",
                upload_to=theater.models.play_directory_path,
            ),
        ),
        migrations.AlterField(
            model_name="actor",
            name="avatar",
            field=models.ImageField(
                default="img/actors/default.jpg",
                upload_to=theater.models.actor_directory_path,
            ),
        ),
    ]
