# Generated by Django 5.2.3 on 2025-07-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theater", "0004_play_image_alter_actor_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(default="The genre is not chosen", max_length=100),
        ),
    ]
