# Generated by Django 5.2.3 on 2025-07-14 00:35

import django.core.validators
import theater.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theater", "0005_alter_genre_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actor",
            name="avatar",
            field=models.ImageField(
                default="img/actors/default.png",
                upload_to=theater.models.actor_directory_path,
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="play",
            name="actors",
            field=models.ManyToManyField(related_name="plays", to="theater.actor"),
        ),
        migrations.AlterField(
            model_name="play",
            name="description",
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name="play",
            name="genres",
            field=models.ManyToManyField(related_name="plays", to="theater.genre"),
        ),
        migrations.AlterField(
            model_name="play",
            name="image",
            field=models.ImageField(
                default="img/plays/default.png",
                upload_to=theater.models.play_directory_path,
            ),
        ),
        migrations.AlterField(
            model_name="play",
            name="title",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="theatrehall",
            name="name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="theatrehall",
            name="rows",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="theatrehall",
            name="seats_in_row",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="row",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="seat",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
