# Generated by Django 5.2.3 on 2025-07-14 00:41

import theater.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theater", "0006_alter_actor_avatar_alter_genre_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actor",
            name="avatar",
            field=models.ImageField(
                default="actors/default.png",
                upload_to=theater.models.actor_directory_path,
            ),
        ),
        migrations.AlterField(
            model_name="play",
            name="image",
            field=models.ImageField(
                default="plays/default.png",
                upload_to=theater.models.play_directory_path,
            ),
        ),
    ]
