# Generated by Django 5.2.3 on 2025-07-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theater", "0007_alter_actor_avatar_alter_play_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="play",
            name="description",
            field=models.TextField(max_length=255),
        ),
    ]
