# Generated by Django 5.2.3 on 2025-09-27 22:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theater", "0008_alter_play_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="performance",
            name="show_time",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["user", "created_at"], name="res_user_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("performance", "row", "seat"),
                name="uniq_performance_row_seat",
                violation_error_message="This seat has just been reserved by someone else. Please choose another.",
            ),
        ),
    ]
